# Generated by Django 5.2.8 on 2025-12-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbrirChamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('inserir_arquivo', models.FileField(upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='ListaChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('em andamento', 'Em andamento'), ('concluído', 'Concluído')], default='aberto', max_length=20)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_pela_ultima_vez', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
