# Generated by Django 5.2.8 on 2025-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_alter_documentos_id_alter_listachamado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='departamento',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
