# Generated by Django 5.0.1 on 2025-12-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_documentos_usuario_alter_documentos_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaChamado',
        ),
        migrations.AddField(
            model_name='documentos',
            name='atualizado_pela_ultima_vez',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='chamados/'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
