# Generated by Django 5.0.1 on 2025-12-24 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_delete_listachamado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('em andamento', 'Em andamento'), ('concluído', 'Concluído')], default='aberto', max_length=20)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_pela_ultima_vez', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='atualizado_pela_ultima_vez',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='status',
        ),
        migrations.AlterField(
            model_name='documentos',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='Documentos/'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
