# Generated by Django 5.0.1 on 2025-12-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_listachamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='atualizado_pela_ultima_vez',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
