# Generated by Django 6.0 on 2026-01-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_documentos_atualizado_pela_ultima_vez'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('em andamento', 'Em andamento'), ('concluído', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listachamado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
