# Generated by Django 6.0.1 on 2026-01-15 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.CharField(blank=True, max_length=45, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='Documentos/')),
                ('atualizado_pela_ultima_vez', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('em andamento', 'Em andamento'), ('concluído', 'Concluído')], default='aberto', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
